### ISSUE TITLE
Calculation accuracy is not correct

### ISSUE THREAD

**Issue by Dio-Zhu** [bugwheels94/math-expression-evaluator#10]
mexp.eval("89*0.11")  -> 9.790000000000001   error

correct :  89*.011 = 9.79

**Comment by amaranth** [comment]
Math in JavaScript is done with floating point arithmetic so this isn't really wrong. If you put this calculation into the console you'll get the same result. Check out https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html if you want the details. Getting the answer you want would require using some kind of arbitrary precision math library (BigDecimal/BigNumber things) which is much slower and harder to use.
