### ISSUE TITLE
Trouble with tokens

### ISSUE THREAD

**Issue by strass** [bugwheels94/math-expression-evaluator#14]
I'm having difficulty registering tokens. I am creating a number of tokens dynamically and attempting to add them to mexp. I have gotten very simple cases to work correctly, but any actual use case is triggering an error. No matter whether I use the `addToken` method or through `eval` directly, I always get the error  `Cannot read property 'length' of undefined at Function.push.f7Mu.Mexp.addToken (lexer.js:72)` (`eval` method is slightly different stack trace but same error)

My token and value fields are unique per token and I am pushing the correct pairs to match up with my tokens. Are there any conditions that I'm missing or which are undocumented? Could it be that my token/value have numeric digits in them?

Thanks for the help

**Comment by bugwheels94** [comment]
Fixed. Added test to test file too so you can check. Thanks for reporting! Cheers

**Comment by bugwheels94** [comment]
You can add numbers to tokens too. It might confuse you in the long run though :|

**Comment by mstokes-f5** [comment]
I am still running into this issue with the latest `master` (`84c8ff4a46b3244c84ee0f3aa767a07ca4971b5c`). I can reproduce this issue using two tokens of size greater than six with the first being longer than the second:

```javascript
'use strict';

const mexp = require('math-expression-evaluator');

const pairs = {
    somethingLong: 5,
    aBitShorter: 3
};
const tokens = Object.keys(pairs).map(key => ({
    type: 3,
    token: key,
    show: key,
    value: key
}));
const result = mexp.eval('somethingLong + aBitShorter', tokens, pairs);
console.log(result);
```

This results in a sparse array for which simple length checks are insufficient to determine if `newAr[x]` will be undefined. If I replace the length checks with checks to see if `newAr[x]` is undefined, things appear to work correctly.

**Comment by bugwheels94** [comment]
Will resolve it ASAP. Thanks
