### ISSUE TITLE
Fiddle does not work

### ISSUE THREAD

**Issue by miloshavlicek** [bugwheels94/math-expression-evaluator#17]
![image](https://user-images.githubusercontent.com/2387790/80748782-c433c780-8b25-11ea-9a30-50110e9331a8.png)

Url of script in example does not exist: http://redhivesoftware.com/calculators/math-expression-evaluator.min.js

**Comment by bugwheels94** [comment]
Took too long. fixed Thanks. Inlined it,  now it wont break
