### ISSUE TITLE
Adding custom token type

### ISSUE THREAD

**Issue by techjewel** [bugwheels94/math-expression-evaluator#19]
I am trying add a formula token like 

max(1,2,3,4,5)   which will show 5
or min(2,5,6,8,1)  which will show 1

Any way to implement these types of tokens.

**Comment by bugwheels94** [comment]
Only One function with 2 argument is supported right now. I have added a test case on how to find maximum of 5 numbers

```

    a.addToken([{
      type: 8,
      token: "maxof2",
      show: "maxof2",
      value: function (a, b, c) {
        return Math.max(a, b)
      }
    }])
    assert.equal(a.eval("maxof2(1,maxof2(maxof2(maxof2(maxof2(2,3),5),6),7))"), 7);
```

**Comment by bugwheels94** [comment]
Feel free to open Issue if you want function with 5 parameters
