### ISSUE TITLE
JS strict mode for math-expression-evaluator? - svelte and rollup

### ISSUE THREAD

**Issue by lukaszpolowczyk** [bugwheels94/math-expression-evaluator#22]
Steps to reproduce:

- `npx degit sveltejs/template my-svelte-project`
- `cd my-svelte-project`
- `npm install`
- `npm install math-expression-evaluator`
- add `import mexp from 'math-expression-evaluator'` to App.svelte
- use `mexp.eval` in App.svelte
- `npm run dev`

Result:
```
Uncaught ReferenceError: assignment to undeclared variable i
tokenize lexer.js:162
lex lexer.js:230
eval postfix_evaluator.js:93
create_fragment$2 App.svelte:15
init index.mjs:1486
App bundle.js:2678
app main.js:3
<anonymous> bundle.js:2697
```

Disabling strict helps:
Setting the optionoutput.strict to false in rollup.config.js

Can math-expression-evaluator be adaptable to JS strict mode?

**Comment by mstokes-f5** [comment]
As a heads up, this looks related to PR #21. I do not know if that PR fixes all of the problem when running in your environment, but it should solve the error in your original post.

**Comment by bugwheels94** [comment]
Hi @lukaszpolowczyk Can you check running version 1.3.4 and update me please?

**Comment by lukaszpolowczyk** [comment]
@bugwheels94 Now there is such a bug when strict mode is on:
```
Uncaught ReferenceError: assignment to undeclared variable key
    tokenize lexer.js:166
    lex lexer.js:230
    eval postfix_evaluator.js:102
    handleKeyup Panel.svelte:21
    prevent_default index.mjs:245
    listen index.mjs:238
    listen_dev index.mjs:1608
    mount bundle.js:2301
    mount_component index.mjs:1411
    mount bundle.js:2870
    mount_component index.mjs:1411
    init index.mjs:1500
    App bundle.js:2917
    app main.js:3
    <anonymous> bundle.js:2936
```

It works with strict mode turned off - just like the previous version.

**Comment by bugwheels94** [comment]
Thanks for the quick reply. Now, I am 90% sure that it will work for you version 1.3.6

Close the issue please if fixed
