### ISSUE TITLE
Additional logs after update

### ISSUE THREAD

**Issue by IAmAdamTaylor** [bugwheels94/math-expression-evaluator#23]
Hi,

I use this package as a dependancy of cssnano in a Gulp build task from the command line. After a recent update, the build task has started producing a lot of unexpected output (~150 lines) every time cssnano runs.

I've narrowed it down to the `console.log` statement below. Is this something that could be disabled, perhaps with CLI flags?

https://github.com/bugwheels94/math-expression-evaluator/blob/da0d0324a71d0278f7555a18c88ace0763ba2060/src/lexer.js#L181

**Comment by bugwheels94** [comment]
Hi, Sorry about that. Fixed in 1.3.7
