### ISSUE TITLE
Memory leak with 0.5sin instead of 0.5*sin

### ISSUE THREAD

**Issue by pimmee** [bugwheels94/math-expression-evaluator#24]
Hello!

There seems to be a bug when you write `0.5sin(1)` instead of `0.5*sin(1)`, which leads to the page freezing with memory leaks and eventually runs out of memory.

To reproduce:
1. Go to the [fiddle yourself](https://jsbin.com/romatuc/edit?html,output) page
2. Add `print("0.5sin(5)")`
3. Run script

![image](https://user-images.githubusercontent.com/33460567/105882808-6249b500-6006-11eb-92dd-9f71c7257623.png)

![image](https://user-images.githubusercontent.com/33460567/105882479-f6ffe300-6005-11eb-9174-2b10b491ef88.png)

**Comment by ankit-gautam-pyxis** [comment]
tq. Will fix in few days/weeks....

**Comment by es183923** [comment]
Also, 

Things such as `print("3 root 9")` also return with an error
shouldn't `print("3root9")` also give an answer, instead of saying `Cannot read property 'type' of undefined`?

**Comment by pimmee** [comment]
Any progress on this?

**Comment by AdamSGit** [comment]
Encountered this issue as well. Any progress ? 
Also, thanks for your time maintaining this lib, it's great and lightweight.

**Comment by bugwheels94** [comment]
Fixed. 1.3.8. Also added test for all of the cases mentioned by @es183923 @pimmee  Sorry for the delay guys
