### ISSUE TITLE
version 1.3.14 resource on npm is 404

### ISSUE THREAD

**Issue by LittleGragon** [bugwheels94/math-expression-evaluator#38]
please check this url:
https://cdn.npmmirror.com/packages/math-expression-evaluator/1.3.14/math-expression-evaluator-1.3.14.tgz

**Comment by bugwheels94** [comment]
Maybe some issue in this cdn?

jsdelive looks fine https://cdn.jsdelivr.net/npm/math-expression-evaluator@1.3.14/dist/browser/math-expression-evaluator.min.js

**Comment by LittleGragon** [comment]
I have double check and it truly due to cdn's issue, thanks.
