### ISSUE TITLE
Is @types/math-expression-evaluator using the wrong return type for `eval`?

### ISSUE THREAD

**Issue by nicklasisraelsson** [bugwheels94/math-expression-evaluator#39]
I'm unsure if this issue should go here or in the Definitely Typed repo.

According to the types `eval` returns a string:

[eval](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/math-expression-evaluator/index.d.ts#L19)
```ts
static eval(exp: string, tokens?: Token[], pair?: object): string;
```

I managed to find that this repo returns a string for "Infinity" here: [postfix_evaluator.js](https://github.com/bugwheels94/math-expression-evaluator/blob/master/src/postfix_evaluator.js#L89)

Shouldn't the return type then be `number | string`?

Will `eval` return a string for any other cases?

If not, perhaps we could change `eval` to return the global [Infinity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity) number?

Then the types at Definitely Typed could be change to have `eval` return `number`

**Comment by dmathisen** [comment]
I just found this. I opened up the same issue on the DefinitelyTyped repo here...
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61508

**Comment by bugwheels94** [comment]
version 2 is TS compliant.
