### ISSUE TITLE
Custom token with an arbitrary amount of inputs

### ISSUE THREAD

**Issue by iGerman00** [bugwheels94/math-expression-evaluator#47]
Awesome library. Using it for user-definable math and some custom tokens, it's really useful and powerful. Recently I've come to an issue where I want to have a 5-input token, for example:
```js
function scale_number(unscaled, to_min, to_max, from_min, from_max) {
    return (to_max-to_min)*(unscaled-from_min)/(from_max-from_min)+to_min;
}
```

I couldn't implement a version of that. Could you perhaps add support for more control over defining tokens?

**Comment by bugwheels94** [comment]
@iGerman00 I will try to do it in 1-2 days as I also want to have that.

**Comment by bugwheels94** [comment]
https://github.com/bugwheels94/math-expression-evaluator/blob/b7592c9551a027bf01c5acb4e3beae43d2a014da/test/index.js#L375

Done.

**Comment by iGerman00** [comment]
Tagging @azerella for type definitions

**Comment by azerella** [comment]
> Tagging @azerella for type definitions

Update incoming! 😄

**Comment by bugwheels94** [comment]
Thanks! addToken method `numberOfArguments: number` is only changed.

**Comment by iGerman00** [comment]
> https://github.com/bugwheels94/math-expression-evaluator/blob/b7592c9551a027bf01c5acb4e3beae43d2a014da/test/index.js#L375
> 
> Done.

Awesome, trying it out right now, it works pretty well, but is there no way to work with undefined arguments?
For example:

```ts
const noiseToken = {
  type: 8,
  token: 'noise',
  show: 'noise',
  numberOfArguments: 3,
  value: function (x: number, y?: number | undefined, seed?: number | undefined) {
    const noise = new Noise(seed ? seed : Math.random());
    const result = noise(x, y ? y : 50);
    console.log(result);
    return result;
  },
};
```

That works but only when all 3 arguments are defined, when any one or more of them are undefined it fails to evaluate. It would be nice to have that functionality.

As for the type definitions, I think the value property on the Token type has also changed now with an arbitrary number of arguments

**Comment by bugwheels94** [comment]
@iGerman00 ah yes, value is also having types changed with numberOfTokens.

I am not able to understand why any argument will be undefined. Are you passing noise(1,,2) or noise(1) or noise(1,2)?

First case will be very hard to implement while second and third case are plausible

**Comment by iGerman00** [comment]
Pardon the confusion, I meant the latter. For example:
The noise() function in the value function takes X, Y and Seed, and returns a number, but users might not necessarily need to input the Y and Seed in my case.

If I were to just evaluate `noise(10)` - only the X position parameter of the noise function is defined, so I want it to get some arbitrary seed and some pre-defined Y position on its own.
`noise(10, 333)` would pass the X position and the seed to the function, so it only needs to set the Y
And of course `noise(10, 20, 333)` would pass all 3

And then handle it in the token value function with if statements: 
```js
if (!seed) const seed = Math.random();
```
Or something like that

**Comment by azerella** [comment]
> Tagging @azerella for type definitions

Have raised a PR for the new parameter :) 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61121

**Comment by bugwheels94** [comment]
@iGerman00 I am afraid that I won't be able to do it. The change that you requesting will require me to tweak automatic parenthesis closure and disable that in your case.  This repo is 7 years old and I dont actively do anything here, just fix bug or minor tweaks that dont require loads of thinking.

**Good news** is that you can do `noise`, `noiseWithoutSeed` etc. to get what you want.

Cheers

**Comment by iGerman00** [comment]
No problem, thanks for looking into it!
