### ISSUE TITLE
root method not calculate with custom token

### ISSUE THREAD

**Issue by HrDelwar** [bugwheels94/math-expression-evaluator#48]
I am trying to convert a number nagative to positive  under root function. I register a custom token name positive who handle calculation.
my token is `{
            type: 0,
            token: 'positive',
            show: 'positive',
            value: function (a) {
                return Math.abs(a);
            }
        }`
        when my formula is "positive(2-6)" is calculate fine and give me result 4.
        but when my formula is "root(positive(2-6))" is not throw error but the result is NaN.

**Comment by bugwheels94** [comment]
I added test for your use case: https://github.com/bugwheels94/math-expression-evaluator/blob/bcab65826b47fce0c48c83e4f4252db47a2c6fed/test/index.js#L389

CICD test passed https://github.com/bugwheels94/math-expression-evaluator/runs/7197156277?check_suite_focus=true#step:5:139

Do you have other tokens added too? that might be causing some conflict
