### ISSUE TITLE
[Bug] 5.5 * 2.2 gives wrong result

### ISSUE THREAD

**Issue by deviouskoala** [bugwheels94/math-expression-evaluator#51]
5.5 * 2.2 gives 12.100000000000001 which is wrong. It should be 12.1

Tested in 1.4.0 

@bugwheels94

**Comment by deviouskoala** [comment]
Same with:
4.4 * 2.1
4.4 * 2.2
1.1 * 4.4
and so on

**Comment by bugwheels94** [comment]
This is same as JS. Try running these expression in browser console.

**Comment by deviouskoala** [comment]
I see. Thank you @bugwheels94
