### ISSUE TITLE
Fails to execute correct solution on basic equation with division, brackets and subtraction

### ISSUE THREAD

**Issue by givethemheller** [bugwheels94/math-expression-evaluator#52]
I discovered this bug with basic division when there is a bracket set involved.

The solution to 55/(.07-.04) = 1375, but returns 1374.999...8

I have prepared breaking tests in the following fork/branch
https://github.com/givethemheller/math-expression-evaluator/tree/heller/odd-paren-behavior

**Comment by givethemheller** [comment]
PR with changes for sake of easy reference.
https://github.com/bugwheels94/math-expression-evaluator/pull/53

**Comment by bugwheels94** [comment]
This is expected. This is how JS works
