### ISSUE TITLE
Running any evaluations a reasonable amount of times per second produces a forever-rising CPU usage

### ISSUE THREAD

**Issue by iGerman00** [bugwheels94/math-expression-evaluator#67]
Here I am again, with my obscure usage of your awesome library haha.

So, recently I bumped it to the latest version, about 3 weeks ago if my memory serves me. Ever since a couple users of my site have noticed a problem with math automations - they start to lag massively with the growing amount of calls to Mexp.

I have been able to reproduce the issue on [your JSBin](https://jsbin.com/tufevuraba/edit?html,output) too, replace the script tag with my code, and open the performance monitor in devtools and you will be able to see it. Be careful however, it may crash the tab.
```js
<script>
      const mexp = new Mexp()
  function yourFunction(){
    // do whatever you like here
    print("2+1")
    print("2+2")
    print("2+3")
    print("2+4")
    print("2+5")
    print("2+6")
    print("2+7")
    print("2+8")
    setTimeout(yourFunction, 17);
}

yourFunction();

  function print(str){
    document.body.appendChild(document.createTextNode(str+" evaluates to "+mexp.eval(str)));
    document.body.appendChild(document.createElement("hr"));
  }
</script>
```

This has not happened before to my knowledge, so some commit has introduced this bug. I'd really appreciate it if you could look into it soon, since a lot of user-generated stuff on my site is using Mexp and it would be quite annoying if most projects start lagging within 30 seconds of playing. 

<sub>P.S. [Live example :)](https://vizzy.io/editor?project=tZOFXEEHI8S6cxVaVNYCu). Ignore the ugly visuals haha. Press the play button, and observe the update time counters gradually rising as the song is playing. The calculations are all very simple multiplications, and there are 6 of them. It's the equivalent of running the code I sent above, in terms of Mexp.</sub>

**Comment by bugwheels94** [comment]
@iGerman00 give me 1-2 days max

**Comment by iGerman00** [comment]
Huh, yeah, that makes sense about the DOM. I can confirm it doesn't happen without that in the example. Doesn't make sense for my actual use case, though - I'm not creating any DOM elements there. For some reason it just rises infinitely. Not the heap size, the cpu usage specifically, and it gets worse over time. I was really stumped so I went to check 
in the example and forgot about the DOM. The thing that confuses me is I didn't change my code, but semi-recently upgraded Mexp from 1.3.0 iirc to 2.0, and it started happening since then. But I reviewed your commits and didn't really anything in there either. Real weird stuff

**Comment by iGerman00** [comment]
Aha, got it! Our previous implementation was a bit jank but for some reason not jank enough to cause issues until now. No idea why, but I fixed it. We were creating a new Mexp() every update, I guess maybe it wasn't being properly destroyed. Regardless thanks for the help!
