### ISSUE TITLE
Incorrect result of root function evaluation

### ISSUE THREAD

**Issue by faiwer** [bugwheels94/math-expression-evaluator#7]
Hello. Please look at next code:
```
mea.eval('root(4-(2-1)^2)'); // 3
mea.eval('root(4-1^2)'); // 1.732050807568877
mea.eval('(4-(2-1)^2)^.5'); // 1.732050807568877
```

**Comment by bugwheels94** [comment]
Took me years but I did it! Solved in latest commit and published

mea.eval('root(4-(2-1)^2)'); // returns 1.73
mea.eval('root(4-1^2)'); // 1.732050807568877
mea.eval('(4-(2-1)^2)^.5'); // 1.732050807568877
