### ISSUE TITLE
Something is wrong with Result

### ISSUE THREAD

**Issue by swancai** [bugwheels94/math-expression-evaluator#70]
Hello, sir. Here is a problem:
1. ES:  
 ```javascript
  const Mexp = require('math-expression-evaluator');
  const math = new Mexp();
  console.log( math.eval(`44.23 + 65.53`) ); 
```
2. We expect the result is 109.76;

3. However, the result is still 109.75999999999999 .

We hope it will be fixed. I look forward to hearing from you soon.
Thx. Best wishes.

**Comment by bugwheels94** [comment]
https://stackoverflow.com/questions/588004/is-floating-point-math-broken

This is JS not this library. tq

**Comment by swancai** [comment]
> 

OK. Thanks.
