### ISSUE TITLE
[Help requested] Troubles with tokens

### ISSUE THREAD

**Issue by Xylofonoda** [bugwheels94/math-expression-evaluator#73]
Hey I just started using your library recently for rather regular evaluations that have a simple answer, but now i kind of just added a figure system that takes the figures off the server and makes them countable using a stringified code that comes from the server response.

```

const figureItem: Token[] = figureTokens.map(figure => ({
      type: 6,
      value: figure.result,
      token: figure.code,
      show: figure.code,
      precedence: 6
    }));

    try {
      const value = newStatement ? mexp.eval(newStatement, figureItem, {}) : undefined;

      return {
        statement: newStatement,
        acreage: value !== undefined ? value : 0,
        statementIsValid: true,
      };
    }

Here is the log from the figureItem.

precedence: 0
show: "s3921839"
​​token: "s3921839"
​​type: 6
​​value: 30

```

What I basically want this thing to do is that when the newStatement is 5+5+ "s3921839"(userwritten figure code) I want the evaluation to be 40.

If you could help id be very grateful thank you !

**Comment by bugwheels94** [comment]
Happy to help! You are looking for math constant type i guess

precedence: 0
show: "s3921839"
​​token: "s3921839"
​​type: Mexp.TOKEN_TYPES.CONSTANT // or put 3 
​​value: 30

**Comment by hurnik-firstis** [comment]
> 

Yes thank you sir you helped me!
