### ISSUE TITLE
mexp.eval("sin(pi/2)") returns 0.027412133592044 instead of 1

### ISSUE THREAD

**Issue by MiraiTunga** [bugwheels94/math-expression-evaluator#79]
mexp.eval("sin(pi/2)") returns 0.027412133592044

was expecting 1

https://www.wolframalpha.com/input?i=sin%28pi%2F2%29

**Comment by bugwheels94** [comment]
By default it takes values in degree mode. For expected result do

mexp.math.isDegree = false
mexp.eval("sin(pi/2)")
