### ISSUE TITLE
mexp.eval("0 + 11 * 15.64") returns 172.04000000000002 instead of 172.04

### ISSUE THREAD

**Issue by IceApriler** [bugwheels94/math-expression-evaluator#80]
mexp.eval("0 + 11 * 15.64") returns 172.04000000000002 instead of 172.04

![image](https://github.com/bugwheels94/math-expression-evaluator/assets/29689307/c3672b32-d201-4c54-b2d4-2a966311ec8d)

Hello, How to fix it ? I need help. Thank you.

**Comment by bugwheels94** [comment]
Its normal. Please read: https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by IceApriler** [comment]
> Its normal. Please read: https://stackoverflow.com/questions/588004/is-floating-point-math-broken

I thought the "math-expression-evaluator" library was created to solve the js floating-point accuracy problem.

**Comment by IceApriler** [comment]
I tried to solve this problem, and the method was enough to meet the requirements of my project.

```js
this.mexp = new Mexp()

/**
 * Although the Mexp library supports the calculation by expression, it still has the accuracy problem.
 * Here, the evalYB method is extended to solve the accuracy problem.
 * Note: The decimal precision here is set to 10 decimal places, which is generally sufficient.
 */
this.mexp.evalYB = (...params) => {
  return this.mexp.eval(...params).toFixed(10) - 0
}
```

Thank you for providing such an excellent library, thank you very much! @bugwheels94

**Comment by mixa9269** [comment]
This worked for me

```
const mexp = new Mexp();

const round14 = n => Math.round(n * 1e14) / 1e14;

mexp.math.add = (a, b) => round14(a + b);

const plusTok = mexp.tokens?.find(t => t.token === '+');
if (plusTok) plusTok.value = mexp.math.add;
```
