### ISSUE TITLE
Precedence issue

### ISSUE THREAD

**Issue by calculatorgr** [bugwheels94/math-expression-evaluator#83]
Since you want cos0=cos(0)=1, you should make it to return cos-0=cos(-0)=1. But your program returns cos-0-cos0=cos(-0-cos(0))=cos(-1) != 0. You should correct it, to return cos-0-cos0=cos(-0)-cos(0)=1-1=0.
The same case for other functions, even log and ln.

**Comment by bugwheels94** [comment]
Thanks! Fixed in version 2.0.4
