### ISSUE TITLE
The ts definition wrong or what?

### ISSUE THREAD

**Issue by YongzeYao** [bugwheels94/math-expression-evaluator#84]
<img width="1064" alt="image" src="https://github.com/bugwheels94/math-expression-evaluator/assets/22460339/5a7118a2-7446-45ea-bee5-51bfbe485f17">

**Comment by bugwheels94** [comment]
@YongzeYao May you tell me the version?

**Comment by lasselindqvist** [comment]
Similar kind of problem with Typescript happens with 2.0.4 at least:
It wants a list of tokens as a mandatory parameter:
![image](https://github.com/bugwheels94/math-expression-evaluator/assets/13466645/eb8f02cf-d1c5-4185-a966-696aa30ea108)

`mexp.eval(text, [], {});`
works, but
`mexp.eval(text);`
will not. The second and third parameters should be made optional.

**Comment by lasselindqvist** [comment]
Confirmed that this fixed the issue for me. Thanks.
